title: "ade's site"
email: "192640919+adelynnmckay@users.noreply.github.com"
author: Adelynn McKay
description: "i'm ade. i do things. make stuff. here's some. have fun."
baseurl: ""
url: "https://adeposting.com/"

theme: jekyll-theme-ade

featured_image: "/assets/images/featured_image.jpg"

github:
  username: adelynnmckay

twitter:
  username: adeposting